name: nats-publisher-example
services:
  
  natstelemetryexample1:
    image: natstelemetryexample
    depends_on:
      - nats
      - opcplc
      - opcpublisher
      - redis
    build:
      context: .
      dockerfile: NatsTelemetryExample/Dockerfile
    environment:
      - NATS_URL=nats:4222
      - REDIS_CONNECTION_STRING=redis:6379
  
  natstelemetryexample2:
    image: natstelemetryexample
    depends_on:
      - nats
      - opcplc
      - opcpublisher
      - redis
    build:
      context: .
      dockerfile: NatsTelemetryExample/Dockerfile
    environment:
      - NATS_URL=nats:4222
      - REDIS_CONNECTION_STRING=redis:6379
      
  nats:
    image: nats:2.9.25
    hostname: nats
    command: -c /etc/nats.conf --name nats -p 4222
    volumes:
      - ./nats/nats.conf:/etc/nats.conf
    ports:
      - 7422:7422
      - 4222:4222
      - 1884:1884
    
  redis:
    image: redis/redis-stack:7.2.0-v10
    hostname: redis
    ports:
      - 6379:6379
      - 8001:8001
        
  grafana:
    image: grafana/grafana-oss:11.0.0
    ports:
      - 3000:3000
    
  opcplc:
    image: mcr.microsoft.com/iotedge/opc-plc:2.12.12
    hostname: opcplc
    ports:
      - 50000:50000
    command: --sph --aa --unsecuretransport --fr=1 --sr=2 --ph=opcplc --to --ft=UInt --st=UInt 
    
  opcpublisher:
    image: mcr.microsoft.com/iotedge/opc-publisher:2.9.6
    command: -t=Mqtt
    depends_on:
      - nats
      - opcplc
    environment:
      - MqttClientConnectionString=HostName=nats;Port=1884;UserName=mqtt;Password=pass;UseTls=False;Protocol=v311;NumberOfClientPartitions=1
      - PublishedNodesFile=/appdata/publisher.json
      - AutoAcceptUntrustedCertificates=True
      - MessagingMode=FullNetworkMessages
      - MessageEncoding=Json
      - TelemetryTopicTemplate={RootTopic}
      - DefaultTransport=Mqtt
      - RootTopicTemplate=publisher
      - MqttClientId=publisher
      - BatchSize=1
      - BatchTriggerInterval=1
      - DefaultQualityOfService=AtLeastOnce
      - MqttBrokerUserName=mqtt
      - MqttBrokerPasswordKey=pass
      - MqttBrokerHostName=cloud_1
      - MqttBrokerPort=1884
      #      - MqttBrokerUserName=
      #      - MqttBrokerPasswordKey=
      #      - MqttBrokerHostName=mosquitto
      #      - MqttBrokerPort=1883
      - MqttProtocolVersion=v311
      - MqttBrokerUsesTls=False
    volumes:
      - ./publisher/publisher.json:/appdata/publisher.json  
  